# Generated by Django 4.2.3 on 2023-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('st', 'Учусь'), ('wk', 'Работаю'), ('sd', 'Туплю'), ('md', 'Мамкин миллиардер'), ('rf', 'Ищу мамика')], max_length=50),
        ),
    ]
