# Generated by Django 4.2.3 on 2023-07-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_alter_userprofile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='about_yourself',
            new_name='description',
        ),
    ]
